# Generated by Django 6.0.4 on 2026-04-25 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Glucosa en ayuno', 'Glucosa en ayuno'), ('Perfil lipídico', 'Perfil lipídico'), ('Química sanguínea 6', 'Química sanguínea 6'), ('Química sanguínea 24', 'Química sanguínea 24'), ('Hemoglobina glucosilada', 'Hemoglobina glucosilada'), ('BH completa', 'BH completa'), ('Examen general de orina', 'Examen general de orina'), ('Prueba de función tiroidea', 'Prueba de función tiroidea')], max_length=60, verbose_name='Tipo de análisis')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora de cita')),
                ('fasting_required', models.BooleanField(default=False, verbose_name='Requiere ayuno')),
                ('fasting_hours', models.PositiveIntegerField(default=0, verbose_name='Horas de ayuno')),
                ('fasting_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de ayuno')),
                ('confirm_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de confirmación')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lab.patient')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PreparationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Programado'), ('Prep Started', 'En preparación'), ('Confirmed', 'Confirmado'), ('No Response', 'Sin respuesta'), ('At Risk', 'En riesgo')], default='Scheduled', max_length=20, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='lab.appointment')),
            ],
            options={
                'verbose_name': 'Estado de preparación',
                'verbose_name_plural': 'Estados de preparación',
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje enviado')),
                ('channel', models.CharField(default='SMS', max_length=20, verbose_name='Canal')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lab.appointment')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-sent_at'],
            },
        ),
    ]
