# Generated by Django 6.0.4 on 2026-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meal_extra_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas extra por comida'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meal_profile',
            field=models.CharField(choices=[('light', 'Light Meal (ensalada, fruta, caldo)'), ('normal', 'Normal Meal (comida regular)'), ('high_fat', 'High Fat Meal (grasas, fritos, carnes)')], default='normal', max_length=10, verbose_name='Perfil de última comida'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='fasting_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas de ayuno base'),
        ),
    ]
