# Generated by Django 6.0.4 on 2026-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_add_meal_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='breakfast_type',
            field=models.CharField(choices=[('light', 'Light Meal (ensalada, fruta, caldo)'), ('normal', 'Normal Meal (comida regular)'), ('high_fat', 'High Fat Meal (grasas, fritos, carnes)')], default='light', max_length=10, verbose_name='Desayuno'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dinner_type',
            field=models.CharField(choices=[('light', 'Light Meal (ensalada, fruta, caldo)'), ('normal', 'Normal Meal (comida regular)'), ('high_fat', 'High Fat Meal (grasas, fritos, carnes)')], default='normal', max_length=10, verbose_name='Cena (última comida)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lunch_type',
            field=models.CharField(choices=[('light', 'Light Meal (ensalada, fruta, caldo)'), ('normal', 'Normal Meal (comida regular)'), ('high_fat', 'High Fat Meal (grasas, fritos, carnes)')], default='normal', max_length=10, verbose_name='Almuerzo'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preanalytic_risk',
            field=models.CharField(choices=[('low', 'Low Risk'), ('elevated', 'Elevated Risk')], default='low', max_length=10, verbose_name='Riesgo preanalítico'),
        ),
    ]
