# Generated by Django 6.0.4 on 2026-04-25 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_add_prep_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparationstatus',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Programado'), ('Guidance Sent', 'Guía enviada'), ('Awaiting Meal', 'Esperando confirmación comida'), ('Prep Started', 'En preparación'), ('Confirmed', 'Confirmado'), ('No Response', 'Sin respuesta'), ('No Response Risk', 'Riesgo sin respuesta'), ('At Risk', 'En riesgo')], default='Scheduled', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ProtocolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('guidance', 'Guía preventiva'), ('meal_check_lunch', 'Check almuerzo'), ('meal_check_dinner', 'Check cena'), ('followup_retry', 'Re-envío follow-up'), ('fasting_reminder', 'Recordatorio ayuno')], max_length=24, verbose_name='Tipo de evento')),
                ('scheduled_at', models.DateTimeField(verbose_name='Hora programada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('responded', 'Respondido'), ('expired', 'Expirado')], default='pending', max_length=12, verbose_name='Estado')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje')),
                ('response', models.CharField(blank=True, max_length=20, verbose_name='Respuesta del paciente')),
                ('response_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de respuesta')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_events', to='lab.appointment')),
            ],
            options={
                'verbose_name': 'Evento de protocolo',
                'verbose_name_plural': 'Eventos de protocolo',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
